//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class vaccine
    {
        public int id { get; set; }
        public string vaccine_name { get; set; }
        public string vaccine_type { get; set; }
        public Nullable<double> dose_count { get; set; }
        public string dose { get; set; }
        public Nullable<double> price { get; set; }
    }
}
