//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VaccineEntities : DbContext
    {
        public VaccineEntities()
            : base("name=VaccineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<community> communities { get; set; }
        public virtual DbSet<hospital> hospitals { get; set; }
        public virtual DbSet<producer> producers { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vaccine_producers> vaccine_producers { get; set; }
        public virtual DbSet<vaccine_records> vaccine_records { get; set; }
        public virtual DbSet<vaccine> vaccines { get; set; }
    }
}
